name: Cooking Reminder

on:
  schedule:
    - cron: '0 14 * * *'  # Runs daily at 2:00 PM UTC (10:00 AM EDT)
  workflow_dispatch:  # Allows manual triggering

jobs:
  send-reminder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install python-dotenv
      - name: Run reminder script
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        run: python main.py
